name: ci

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push first image
        run: echo first image
        working-directory: ./node-docker
        id: docker_build_1
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lucasignacio18/node-github:1.0
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
