name: Build and push docker images

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        id: builder1

      - uses: docker/setup-buildx-action@v1
        id: builder2

      - name: Builder first image
        run: echo ${{ steps.builder1.outputs.name }}

      - name: Builder second image
        run: echo ${{ steps.builder2.outputs.name }}

      - name: Build against build image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder1.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          tags: lucasignacio18/node-github:1.0

      - name: Build against build image 2
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.builder2.outputs.name }}
          context: .
          file: ./Dockerfile
          push: true
          tags: lucasignacio18/node-github:2.0
